In [6]:
pip install tensorflow

  Using cached tensorflow-2.11.0-cp39-cp39-win_amd64.whl (1.9 kB)



In [7]:
import tensorflow as tf

In [8]:
x=tf.constant(4,shape=(1,1),dtype=tf.float32)

In [9]:
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [10]:
x=tf.constant([[1,2,3],[4,5,6]],shape=(2,3))

In [11]:
print(x)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [12]:
x=tf.eye(3)

In [13]:
print(x)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [14]:
x=tf.ones((4,3))

In [15]:
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(4, 3), dtype=float32)


In [16]:
x=tf.zeros((3,2,5))

In [17]:
print(x)

tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 2, 5), dtype=float32)


In [18]:
x=tf.random.uniform((2,2),minval=0,maxval=1)

In [19]:
print(x)

tf.Tensor(
[[0.89623404 0.46394992]
 [0.6898029  0.67426634]], shape=(2, 2), dtype=float32)


In [20]:
x=tf.random.normal((3,3),mean=0,stddev=1)

In [21]:
print(tf.cast(x,dtype=tf.float64))

tf.Tensor(
[[-0.51412481 -0.66424161 -2.03140283]
 [-1.25791025 -1.01579988 -0.85212183]
 [ 1.97427475  0.19193357  1.48320639]], shape=(3, 3), dtype=float64)


In [22]:
x=tf.range(9)

In [23]:
x=tf.range(start=0,limit=10,delta=2)

In [24]:
print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [25]:
x=tf.constant([1,2,3])

In [26]:
y=tf.constant([9,8,7])

In [27]:
z=tf.add(x,y)

In [28]:
z=x+y

In [29]:
z=tf.subtract(x,y)

In [30]:
z=x-y

In [31]:
z=tf.divide(x,y)

In [65]:
print(z)

tf.Tensor(
[[ 2.3428602  -0.64813954]
 [ 5.358514   -1.6714163 ]], shape=(2, 2), dtype=float32)


In [32]:
z=x/y

In [33]:
z=tf.multiply(x,y)

In [34]:
z=x*y

In [35]:
z=tf.tensordot(x,y,axes=1)

In [64]:
print(z)

tf.Tensor(
[[ 2.3428602  -0.64813954]
 [ 5.358514   -1.6714163 ]], shape=(2, 2), dtype=float32)


In [36]:
z=x**5

In [63]:
print(z)

tf.Tensor(
[[ 2.3428602  -0.64813954]
 [ 5.358514   -1.6714163 ]], shape=(2, 2), dtype=float32)


In [37]:
x=tf.random.normal((2,3))

In [62]:
print(x)

tf.Tensor(
[[0 3 6]
 [1 4 7]
 [2 5 8]], shape=(3, 3), dtype=int32)


In [38]:
y=tf.random.normal((3,2))

In [61]:
print(y)

tf.Tensor(
[[-0.7842342  -0.26434946]
 [ 0.55170083 -0.14977637]
 [-1.6787572   0.9976668 ]], shape=(3, 2), dtype=float32)


In [39]:
z=tf.matmul(x,y)

In [60]:
print(z)

tf.Tensor(
[[ 2.3428602  -0.64813954]
 [ 5.358514   -1.6714163 ]], shape=(2, 2), dtype=float32)


In [40]:
z=x@y

In [59]:
print(z)

tf.Tensor(
[[ 2.3428602  -0.64813954]
 [ 5.358514   -1.6714163 ]], shape=(2, 2), dtype=float32)


In [41]:
x=tf.random.normal((2,2))

In [42]:
x=tf.constant([0,1,1,2,3,1,2,3])

In [43]:
print(x[:])

tf.Tensor([0 1 1 2 3 1 2 3], shape=(8,), dtype=int32)


In [44]:
print(x[1:])

tf.Tensor([1 1 2 3 1 2 3], shape=(7,), dtype=int32)


In [45]:
print(x[1:3])

tf.Tensor([1 1], shape=(2,), dtype=int32)


In [46]:
print(x[::2])

tf.Tensor([0 1 3 2], shape=(4,), dtype=int32)


In [47]:
print(x[::-1])

tf.Tensor([3 2 1 3 2 1 1 0], shape=(8,), dtype=int32)


In [48]:
indices=tf.constant([0,3])

In [49]:
x_indices=tf.gather(x,indices)

In [50]:
x=tf.constant([[1,2],[3,4],[5,6]])

In [51]:
print(x[0,:])

tf.Tensor([1 2], shape=(2,), dtype=int32)


In [52]:
print(x[0:2,:])

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [53]:
x=tf.range(9)

In [54]:
x

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8])>

In [55]:
x=tf.reshape(x,(3,3))

In [56]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [57]:
x=tf.transpose(x,perm=[1,0])

In [58]:
x

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])>